/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Habit = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'color' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HabitLog = IDL.Record({
  'date' : IDL.Text,
  'done' : IDL.Bool,
  'habitId' : IDL.Text,
  'timeNote' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHabit' : IDL.Func([IDL.Text, IDL.Text], [Habit], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateShareToken' : IDL.Func([], [IDL.Text], []),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getCallerLogs' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(HabitLog)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabitHistory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(HabitLog)],
      ['query'],
    ),
  'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getHabitsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Habit)], ['query']),
  'getLogs' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(HabitLog)], ['query']),
  'getLogsForHabit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Vec(HabitLog)],
      ['query'],
    ),
  'getSharedTracker' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({ 'logs' : IDL.Vec(HabitLog), 'habits' : IDL.Vec(Habit) })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHabit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [HabitLog],
      [],
    ),
  'removeHabit' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Habit = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'color' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HabitLog = IDL.Record({
    'date' : IDL.Text,
    'done' : IDL.Bool,
    'habitId' : IDL.Text,
    'timeNote' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHabit' : IDL.Func([IDL.Text, IDL.Text], [Habit], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateShareToken' : IDL.Func([], [IDL.Text], []),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getCallerLogs' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(HabitLog)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabitHistory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(HabitLog)],
        ['query'],
      ),
    'getHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getHabitsForUser' : IDL.Func([IDL.Principal], [IDL.Vec(Habit)], ['query']),
    'getLogs' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(HabitLog)], ['query']),
    'getLogsForHabit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Vec(HabitLog)],
        ['query'],
      ),
    'getSharedTracker' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'logs' : IDL.Vec(HabitLog),
              'habits' : IDL.Vec(Habit),
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHabit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [HabitLog],
        [],
      ),
    'removeHabit' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };