/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habit {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'color' : string,
}
export interface HabitLog {
  'date' : string,
  'done' : boolean,
  'habitId' : string,
  'timeNote' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHabit' : ActorMethod<[string, string], Habit>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateShareToken' : ActorMethod<[], string>,
  'getAllHabits' : ActorMethod<[], Array<Habit>>,
  'getCallerLogs' : ActorMethod<[string, string, string], Array<HabitLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHabitHistory' : ActorMethod<[string, string, string], Array<HabitLog>>,
  'getHabits' : ActorMethod<[], Array<Habit>>,
  'getHabitsForUser' : ActorMethod<[Principal], Array<Habit>>,
  'getLogs' : ActorMethod<[string, string], Array<HabitLog>>,
  'getLogsForHabit' : ActorMethod<[string, string, string], Array<HabitLog>>,
  'getSharedTracker' : ActorMethod<
    [string],
    [] | [{ 'logs' : Array<HabitLog>, 'habits' : Array<Habit> }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logHabit' : ActorMethod<[string, string, boolean, string], HabitLog>,
  'removeHabit' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];